### PR TITLE
v2

### PR DESCRIPTION
**Pull request by unpredictable**
worked on major update today

changelog:
- add PHD checker (needs fixing on the centring of the elements, I don't know how to do that)
- add blocked/available name checker to the main page
- migrate to Bootstrap v4
- add navbar
- better UI in general

### CODE REVIEW

**Comment by unpredictable** [comment]
There are two known edge cases with this build:

1. Spacing issue with the `[may be inaccurate]` part of the creation date element:

spacing issue

2. Some sort of spacing issue with the navbar, before it turns into mobile mode:

navbar issue

These also *should* be fixed before we merge this.

**Comment by unpredictable** [comment]
Also, the white borders for the user/cape info boxes don't exist for some reason. I don't know how to fix that, I'm bad with CSS

**Comment by unpredictable** [comment]
Also, the alert boxes aren't responsive to mobile displays. This will be fixed later - not a major priority

**Comment by unpredictable** [comment]
> Also, the white borders for the user/cape info boxes don't exist for some reason. I don't know how to fix that, I'm bad with CSS

Fixed.

**Comment by tanpug** [comment]
Most issues are resolved except the "may be inaccurate" superscript overlapping and the alert boxes not being responsive to mobile displays. Merging is a good idea but fixing these issues is top priority

**Comment by unpredictable** [comment]
> 2. Some sort of spacing issue with the navbar, before it turns into mobile mode::

Fixed on its own.... I don't know either

**Pull request merged**
